# Generated by Django 2.2.4 on 2019-09-02 23:06

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=130)),
                ('foto', models.ImageField(blank=True, default='default.jpg', upload_to='students_pics')),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], max_length=130)),
                ('raza', models.CharField(choices=[('blanca', 'Blanca'), ('meztiza', 'Mestiza'), ('negra', 'Afrodescendiente'), ('indigena', 'Indigena')], max_length=120)),
                ('fecha_de_nacimiento', models.DateField(blank=True, default=datetime.datetime(2019, 9, 2, 18, 6, 59, 239926), help_text='Año-Mes-Dia', null=True)),
                ('ci', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('nacionalidad', models.CharField(default='Ecuatoriana', max_length=130)),
                ('curso', models.CharField(blank=True, choices=[('i_1', 'Inicial 1'), ('i_2', 'Inicial 2'), ('i_3', 'Inicial 3')], max_length=130)),
                ('domicilio', models.TextField()),
                ('embarazo_de_la_madre_con_control', models.BooleanField(blank=True, default=True)),
                ('parto_de_la_madre', models.CharField(blank=True, choices=[('normal', 'Normal'), ('complicado', 'Complicado')], max_length=120)),
                ('tiene_discapacidad', models.BooleanField(default=False)),
                ('tipo_de_discapacidad', models.CharField(blank=True, choices=[('fisica', 'Fisica'), ('mental', 'Mental')], max_length=125)),
                ('parte_afectada_por_discapacidad', models.CharField(blank=True, max_length=130)),
                ('tipo_de_alimentacion', models.CharField(max_length=130)),
                ('desde_que_edad_comio_solidos', models.FloatField(default=3)),
                ('hasta_que_edad_tomo_leche_materna', models.FloatField(default=3)),
                ('tipo_de_sangre', models.CharField(max_length=125)),
                ('alergias', models.TextField(blank=True)),
                ('enfermedades', models.TextField(blank=True)),
                ('operaciones', models.TextField(blank=True)),
                ('nombre_del_representante', models.CharField(max_length=130)),
                ('ci_del_representante', models.PositiveSmallIntegerField()),
                ('nacionalidad_del_representante', models.CharField(default='Ecuatoriana', max_length=130)),
                ('telefono_del_representante', models.IntegerField()),
                ('estado_civil_del_representante', models.CharField(blank=True, choices=[('soltero/a', 'Soltero/a'), ('casado/a', 'Casado/a')], max_length=125)),
                ('representante_vive_con_estudiante', models.BooleanField()),
                ('domicilio_del_representante', models.TextField(blank=True)),
                ('lugar_trabajo_del_representante', models.TextField(blank=True)),
                ('el_representante_es_el_padre_o_la_madre', models.BooleanField(default=True)),
                ('nombre_de_la_madre', models.CharField(blank=True, max_length=130)),
                ('ci_de_la_madre', models.PositiveSmallIntegerField(blank=True)),
                ('nacionalidad_de_la_madre', models.CharField(blank=True, default='Ecuatoriana', max_length=130)),
                ('telefono_de_la_madre', models.IntegerField()),
                ('estado_civil_de_la_madre', models.CharField(blank=True, choices=[('soltero/a', 'Soltero/a'), ('casado/a', 'Casado/a')], max_length=125)),
                ('madre_vive_con_hijo', models.BooleanField(blank=True, default=True)),
                ('domicilio_de_la_madre', models.TextField(blank=True)),
                ('lugar_trabajo_de_la_madre', models.TextField(blank=True)),
                ('nombre_del_padre', models.CharField(blank=True, max_length=130)),
                ('ci_del_padre', models.PositiveSmallIntegerField(blank=True)),
                ('nacionalidad_del_padre', models.CharField(blank=True, default='Ecuatoriana', max_length=130)),
                ('telefono_del_padre', models.IntegerField(blank=True)),
                ('estado_civil_de_padre', models.CharField(blank=True, choices=[('soltero/a', 'Soltero/a'), ('casado/a', 'Casado/a')], max_length=125)),
                ('padre_vive_con_hijo', models.BooleanField(default=True)),
                ('domicilio_del_padre', models.TextField(blank=True)),
                ('lugar_trabajo_del_padre', models.TextField(blank=True)),
                ('documentos_adjuntos', models.FileField(blank=True, upload_to='')),
                ('profesora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
