# Generated by Django 2.2.4 on 2019-09-02 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 9, 2, 18, 7, 26, 865177), help_text='Año-Mes-Dia', null=True),
        ),
    ]
