# Generated by Django 2.2.4 on 2019-09-06 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20190903_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='documentos_adjuntos',
            field=models.FileField(blank=True, null=True, upload_to='atachdocs/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 9, 6, 14, 3, 37, 622496), help_text='Año-Mes-Dia', null=True),
        ),
    ]
